# Modified Space Duck
# From github.com/pineapplegiant/spaceduck
colors:
  primary:
    # background: '#222532'
    # foreground: '#bead9d'
    background: '#fceee0'
    foreground: '#4a5067'


  normal:
    black:   '#000000'
    red:     '#ce6f8f'
    green:   '#5ccc96'
    yellow:  '#f2ce00'
    blue:    '#00a3cc'
    magenta: '#ce6f8f'
    cyan:    '#00a3cc'
    white:   '#ffffff'

  bright:
    black:   '#686f9a'
    red:     '#ce6f8f'
    green:   '#5ccc96'
    yellow: '#f2ce00' # same
    blue:    '#00a3cc' # same
    magenta: '#ce6f8f' # same
    cyan: '#00a3cc'
    white:   '#f0f1ce'
