# Modified Space Duck
# From github.com/pineapplegiant/spaceduck
colors:
  primary:
    background: '#0f111b'
    foreground: '#b3a1e6'

  normal:
    black:   '#000000'
    red:     '#e33400'
    green:   '#5ccc96'
    yellow: '#f2ce00'
    blue:    '#00a3cc'
    magenta: '#ce6f8f'
    cyan: '#00a3cc'
    white: '#ffffff'

  bright:
    black:   '#686f9a'
    red:     '#e33400'
    green:   '#5ccc96'
    yellow: '#f2ce00' # same
    blue:    '#00a3cc' # same
    magenta: '#ce6f8f' # same
    cyan: '#00a3cc'
    white:   '#f0f1ce'
